export const INCREASE_MUSCLE_MASS = 'INCREASE_MUSCLE_MASS';
export const INCREASE_MUSCLE_STRENGTH = 'INCREASE_MUSCLE_STRENGTH';
export const WEIGHT_LOSS = 'WEIGHT_LOSS';
export const MAINTAINING_THE_FORM_ALREADY_ACHIEVED = 'MAINTAINING_THE_FORM_ALREADY_ACHIEVED';